FROM debian:sid
ENV PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=1.0
RUN set -eux; \
    apt-get update && apt-get install -y calibre; \

RUN pip install "poetry==$POETRY_VERSION"
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN set -eux; \
    poetry config virtualenvs.create false; \
    poetry install --no-dev
COPY . .

ENTRYPOINT ["python", "-m", "p2kbot", "convsrv"]
